export const SET_REMOTE_DATA = '@/SET_REMOTE_DATA';
export const SET_FILTER_VALUE = '@/SET_FILTER_VALUE';
export const SET_CURRENT_USER = '@/SET_CURRENT_USER';

export const OPEN_NOTIFICATION_BAR = '@/OPEN_NOTIFICATION_BAR';
export const CLOSE_NOTIFICATION_BAR = '@/CLOSE_NOTIFICATION_BAR';
